[window]
dimensions = { columns = 200, lines = 60 }
padding = { x = 8, y = 4 }
opacity = 0.85

[cursor]
style = "Beam"

[scrolling]
history = 100000
multiplier = 3

[font]
size = 11.0
offset = { x = 0, y = 4 }
normal = { family = "Hack Nerd Font", style="Regular" }
bold = { family = "Hack Nerd Font", style="Bold" }
italic = { family = "Hack Nerd Font", style="Italic" }
bold_italic = { family = "Hack Nerd Font", style="Bold Italic" }


[general]
import = [
    "~/dotfiles/packages/alacritty/.config/alacritty/themes/themes/duskfox.toml" 
]
live_config_reload = true

[env]
TERM = "tmux-256color"